name: hsnix-nixdrv
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - hashable ^>= 1.3
  - unordered-containers ^>= 0.2
  - hnix ^>= 0.16
  - prettyprinter ^>= 1.7
  - data-fix ^>= 0.3
  - hsnix-core
  - directory ^>= 1.3

library:
  source-dirs: src
