name: hsnix-drv
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2 && < 2
  - bytestring >= 0.10 && < 1
  - containers >= 0.6 && < 1
  - unordered-containers >= 0.2 && < 1
  - vector >= 0.12 && < 1
  - hashable >= 1.3 && < 2
  - cryptonite >= 0.29 && < 1
  - nix-derivation >= 1.1 && < 2
  - hnix-store-core >= 0.5 && < 1
  - hnix-store-remote >= 0.5 && < 1
  - directory >= 1.3 && < 2
  - unix >= 2.7 && < 3
  - hsnix-core

library:
  source-dirs: src
  other-modules:
    - HsNix.Derivation.Drv.Internal.Derivation
    - HsNix.Derivation.Drv.Internal.Hash
    - HsNix.Derivation.Drv.Internal.Nar
