name: hsnix-drv
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - bytestring ^>= 0.10
  - containers ^>= 0.6
  - unordered-containers ^>= 0.2
  - vector ^>= 0.12
  - hashable ^>= 1.3
  - cryptonite ^>= 0.29
  - nix-derivation ^>= 1.1
  - hnix-store-core ^>= 0.5
  - hnix-store-remote ^>= 0.5
  - directory ^>= 1.3
  - unix ^>= 2.7
  - hsnix-core

library:
  source-dirs: src
  other-modules:
    - HsNix.Derivation.Drv.Internal.Derivation
    - HsNix.Derivation.Drv.Internal.Hash
    - HsNix.Derivation.Drv.Internal.Nar
