name: hsnix-core
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - cryptonite ^>= 0.29
  - bytestring ^>= 0.10
  - hashable ^>= 1.3
  - nix-archive

library:
  source-dirs: src
  dependencies:
    - memory ^>= 0.16
    - unordered-containers ^>= 0.2
    - mtl ^>= 2.2
    - template-haskell ^>= 2.17
