name: hsnix-core
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2 && < 2
  - unordered-containers >= 0.2 && < 1
  - mtl >= 2.2 && < 3
  - cryptonite >= 0.29 && < 1
  - memory >= 0.16 && < 1
  - bytestring >= 0.10 && < 1
  - hashable >= 1.3 && < 2

library:
  source-dirs: src
