name: hsnix-core
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - text ^>= 1.2
  - containers ^>=0.6
  - unordered-containers ^>= 0.2
  - mtl ^>= 2.2
  - cryptonite ^>= 0.29
  - memory ^>= 0.16
  - bytestring ^>= 0.10
  - hashable ^>= 1.3
  - template-haskell ^>= 2.17
  - th-lift-instances ^>= 0.1.20 # for map
  - directory ^>=1.3

library:
  source-dirs: src
