name: nix-archive
version: 0.1.0.0
author: "Jose Lane"
license: MIT
maintainer: dariankline@outlook.com

extra-source-files:
  - tests/spec/files/*

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

dependencies:
  - base ^>= 4.15
  - bytestring ^>= 0.11.2
  - containers ^>= 0.6.6
  - binary ^>= 0.8

library:
  source-dirs: src
  dependencies:
    - filepath ^>= 1.4.100
    - directory ^>= 1.3.8
    - unix ^>= 2.8
    - hashable ^>= 1.3
    - template-haskell

tests:
  spec:
    main: Main.hs
    source-dirs: tests/spec
    dependencies:
      - hspec ^>= 2.8
      - nix-archive
